version: '3.9'
services:
  webapp:
    container_name: sample-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:mysql://mysql:3306/sampleDB?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: password
    volumes:
      - "webapp-volume:/usr/local/tomcat/webapps"
      - "./application-prod.yml:/usr/local/tomcat/webapps/tap-sdk-sample-app/WEB-INF/classes/application.yml"
    depends_on:
        - mysql

  mysql:
    container_name: sample-mysql
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sampleDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - "mysql-volume:/var/lib/mysql"

volumes:
    webapp-volume:
    mysql-volume: