spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sampleDB?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none # or validate for production
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    cache: false # true for production
  security:
    user:
      name: admin
      password: admin
  actuator:
    health:
      db:
        enabled: true
    metrics:
      export:
        prometheus:
          enabled: true

server:
  port: 8080
  servlet:
    context-path: /tap-sdk-sample-app

# Security configurations might need to be adjusted based on your Spring Security setup

# Logging configurations
logging:
  level:
    org:
      springframework: ERROR
      hibernate: ERROR # Or INFO for less verbose logging
    root: INFO

sdk:
  api:
    key: a35d5d0fb13a0e608a149f4ffa2a9916
    secret: fc5bf2bd-161d-463a-8b9e-43ea33920fbd
    url: https://dev.sdp.hsenidmobile.com/sdk/subscription/authorize
  redirect:
    url: https://dev.sdp.hsenidmobile.com/tap-sdk-sample-app/sdk/
  app:
    url: https://dev.sdp.hsenidmobile.com
    id: APP_000040
    password: f9fba739bfffba8d19b91c7970b81161
    unsub: /subs/unregistration
    charge: /subscription/subscriberChargingInfo
ssl:
  validate:
    cert: false # true for production
